### ISSUE TITLE
Add instructions to find your city's relevant IDs

### ISSUE THREAD

**Issue by thecristen** [datamade/councilmatic-starter-template#1]
Hi! I know these docs are very much under development. I'm playing around with this and I'm kind of stuck at the editing `settings_jurisdiction.py`. I'm not intimately familiar with OCD so I'm not sure how to set the `OCD_CITY_COUNCIL_ID` and `OCD_JURISDICTION_ID` for my city.
[This link in the OCD docs seems to be long dead](http://editor.opencivicdata.org/geo/select/). Is [http://ocd.datamade.us/jurisdictions/](http://ocd.datamade.us/jurisdictions/) the right resource? And how might I approach adding a new city? ;)

**Comment by cathydeng** [comment]
hey @thecristen!

yes, the OCD docs are very out of date, I should add a note about that to the readme. http://ocd.datamade.us/jurisdictions/ is indeed the right place to look for jurisdictions.  is your city already in the OCD API? if not, the first step would be to write some scrapers to populate the data [here](https://github.com/opencivicdata/scrapers-us-municipal). what city are you trying to deploy councilmatic for?
