### ISSUE TITLE
Fix INSTALLED_APP load order

### ISSUE THREAD

**Issue by patcon** [datamade/councilmatic-starter-template#2]
I've only just now realized the root of some odd behaviour I've come across. It seems that Django expects overriding apps to be listed first in INSTALLED_APPS list:
https://stackoverflow.com/questions/31925458/importance-of-apps-orders-in-installed-apps

This affects both [templates override order](https://docs.djangoproject.com/en/1.9/ref/templates/api/#django.template.loaders.app_directories.Loader) and management commands.

Making this change in this template, as well as chicago and nyc, will make it so that:
1) `loaddata` command can be overriden
2) template partials can be overridden properly just by dropping new files into `mycity/templates/partials/somepartial.html` (supposing the original location was in `councilmatic_core/templates/partials/somepartial.html`)

**Comment by patcon** [comment]
Would be nice to move the partials into a namespaced dir like we do with other templates.

`councilmatic_core/templates/partials/somepartial.html` :arrow_right: `councilmatic_core/templates/councilmatic_core/partials/somepartial.html`

That way, when we override in our city-specific repo, it's easy to review the partials that come from core to do things like push the customizations upstream or diff them against the upstream ones for updates. Better not to mix the partials from the city-specific app with the core app, right?

**Comment by fgregg** [comment]
This looks good to me, @cathydeng ?

**Comment by evz** [comment]
Just fixed this with f0d7a4e9f31d3841c327e58bfc3c9b3578302610

**Comment by patcon** [comment]
No sweat :) thanks for all the things!
